image: golang

variables:
  HTTP_PROXY: "prx-1.vsrv.ir:7070"
  HTTPS_PROXY: "prx-1.vsrv.ir:7070"
  NO_PROXY: "vada.ir,git.vada.ir"

stages:
  - lint
  - build

lint:
  stage: lint
  tags:
    - docker
    - golang
  script:
    - export GOBIN=$GOPATH/bin
    - export PATH=$PATH:$GOBIN
    - make lint

build:
  stage: build
  tags:
    - docker
    - golang
  script:
    - export GOBIN=$GOPATH/bin
    - export PATH=$PATH:$GOBIN
    - make build
  artifacts:
    paths:
      - migrate
