image: golang

variables:
  HTTP_PROXY: "172.17.0.1:7070"
  HTTPS_PROXY: "172.17.0.1:7070"

stages:
  - lint
  - build

lint:
  stage: lint
  tags:
    - docker
    - golang
  script:
    - export GOBIN=$GOPATH/bin
    - export PATH=$PATH:$GOBIN
    - make lint

build:
  stage: build
  tags:
    - docker
    - golang
  script:
    - make build
  artifacts:
    paths:
      - migrate
